[package]
name = "fishbowl"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
burn = { workspace = true, features = ["fusion", "autotune"] }
conway = { path = "../../crates/conway" }
clap = { workspace = true, features = ["derive"] }

piston = { workspace = true}
piston2d-graphics = { workspace = true}
pistoncore-glutin_window = { workspace = true}
piston2d-opengl_graphics = { workspace = true}
gl = {workspace = true}

[lints]
workspace = true

[features]
default = ["wgpu"]
wgpu = ["burn/wgpu"]