[package]
name = "conway_benchmark"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
clockmill = { path = "../../crates/clockmill" }

burn = { workspace = true, features = ["fusion", "autotune"] }
clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

# Bug in burn/cuda deps; pinned to force "nvrtc" for cudarc:
cudarc = { workspace = true, features = ["nvrtc"], optional = true }

[lints]
workspace = true

[features]
default = []
cuda = ["burn/cuda"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]
