[package]
name = "conway_benchmark"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
burn = { workspace = true, features = ["fusion", "autotune", "wgpu"] }
clockmill = { path = "../../crates/clockmill" }
clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

[lints]
workspace = true

[features]
default = ["wgpu"]
cuda = ["burn/cuda"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]
