[workspace]
# Require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
    "examples/*",
]

[workspace.package]
version = "0.0.1"
repository = "https://github.com/crutcher/clockmill"
rust-version = "1.90.0"
edition = "2024"
license = "MIT"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
double_must_use = "allow"
doc_markdown = "warn"


[patch.crates-io]
# Use pre-release version of burn for 0.19.0.
burn = { git = "https://github.com/tracel-ai/burn", rev ="8c5873a77996a4187301b4b5d39ee670a572d63f" }
bimm-contracts = { git = "https://github.com/crutcher/bimm-contracts", rev = "396b61ac4ad41d9bb43fbafefbf4cf1c0312578f" }


[workspace.dependencies]
burn = "^0.19.0"
bimm-contracts = "^0.4.3"

indicatif = "^0.18.0"

clap = "^4.5.47"

criterion = { version = "^0.7.0" }

piston = "^1.0.0"
piston2d-graphics = "^0.45.0"
pistoncore-glutin_window = "^0.72.0"
piston2d-opengl_graphics = "^0.89.0"
gl = "^0.14.0"
