[package]
name = "conway_speedtest"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
burn = { workspace = true, features = ["fusion", "autotune", "wgpu"] }
conway = { path = "../../crates/conway" }
clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

[lints]
workspace = true

[features]
default = ["wgpu"]
cuda = ["burn/cuda"]
metal = ["burn/metal"]
wgpu = ["burn/wgpu"]
