[package]
name = "scratch"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
burn = { workspace = true, features = ["fusion", "autotune", "wgpu"] }
conway = { path = "../../crates/conway" }
clap = { workspace = true, features = ["derive"] }
indicatif = { workspace = true }

bimm-contracts = { workspace = true, features = ["burn"] }

[lints]
workspace = true
