[package]
name = "clockmill"
description = "Constant-Volume-Grid Simulations for Burn"
documentation = "https://docs.rs/clockmill/latest"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
burn = { workspace = true }
bimm-contracts = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["cuda", "wgpu", "vulkan"] }

# For benchmarks:
criterion = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "lbm"
harness = false
