[package]
name = "clockmill"
description = "Constant-Volume-Grid Simulations for Burn"
documentation = "https://docs.rs/clockmill/latest"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[[bench]]
name = "lbm"
harness = false


[features]
default = []


[dependencies]
burn = { workspace = true }
bunsen = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
nearly = { workspace = true }

# For benchmarks:
criterion = { workspace = true }


